### ISSUE TITLE
Redesign category selection

### ISSUE THREAD

**Issue by Polarts** [Polarts/sentispace#55]
# Description
The current category selection UX is rather confusing and feels unintuitive.
I'd rather update it to something similar to past versions, that'd look like the GitHub mobile app's label selection page. 

# Current Design
<img src="https://github.com/user-attachments/assets/1faf53f2-1ae7-4656-97e0-3fd7430a63e9" width="400px">

# Target Design
<img src="https://github.com/user-attachments/assets/a40a973e-f7de-4c11-9c40-59b084f5d1cb" width="400px">

**Comment by Ziv89** [comment]
I've started to work on that
