### ISSUE TITLE
Time picker improvements

### ISSUE THREAD

**Issue by Polarts** [Polarts/sentispace#56]
# Description
![image](https://github.com/user-attachments/assets/30875a46-b6c8-4947-9e73-0c72f927230f)
The time picker is a component located in the activity add/edit form. Functionally it works well, but right now the user experience is lacking.
The component is located at `src/components/input/time-picker` in the code.

# Tasks
- [ ] Allow backspace when typing the time. Not being allowed to erase makes for a very uncomfortable user experience.
- [ ] Add a toggle for 24h mode. This should also appear in the settings page and be saved in storage.

**Comment by Ziv89** [comment]
I am working on it.
