### ISSUE TITLE
Redundant version Method issue in visual code Database.ts file

### ISSUE THREAD

**Issue by Ziv89** [Polarts/sentispace#57]
While running the project in visual code there is an issue in the the section : 

 **version(arg0: number) {
    throw new Error('Method not implemented.')
  }**
in Database.ts.  it causes errors and the page will be blank while running the project:

The issues in the code seems to be  from the attempt to override or redefine methods that are already provided by the Dexie library, deleting this section seems to fix the error.

![blankpage](https://github.com/user-attachments/assets/843042f2-c01a-4142-8d45-4ee2a10ef104)
 ![Captureerror](https://github.com/user-attachments/assets/554e09e2-f90c-4fbd-b2ac-93ecc06e0bf7)

**Comment by Polarts** [comment]
I'm sorry, but I don't see this anywhere in the project's codebase. 
I also ran it now to verify with a fresh clone and there's no such error.
Where did you find it?

**Comment by Ziv89** [comment]
> I'm sorry, but I don't see this anywhere in the project's codebase. I also ran it now to verify with a fresh clone and there's no such error. Where did you find it?

I've downloaded the whole project and tried to run it in visual code and then the section appeared in Database.ts.
[sentispace-main.zip](https://github.com/user-attachments/files/16942709/sentispace-main.zip)

**Comment by Polarts** [comment]
> I've downloaded the whole project and tried to run it in visual code and then the section appeared in Database.ts. [sentispace-main.zip](https://github.com/user-attachments/files/16942709/sentispace-main.zip)

I assume you have some extension in VSCode that did it. I opened the zip in the link and there's no such line in Database.ts
